### ISSUE TITLE
unable to identify RN1 required component

### ISSUE THREAD

**Issue by crijopoga** [zzattack/xbox-cpu-interposer#1]
i was looking for required parts using the specified BOM file but i was unable to find any "R_Network04". any more specific data about it please?

**Comment by j44dge** [comment]
I'm also wondering about this.

**Comment by j44dge** [comment]
Also just to add, is there any guide for this? Do people need to modify any resistors on the OG Xbox board for V-Core voltage etc??

**Comment by AR1972** [comment]
the components are the same as the old interposer
https://github.com/N64-Freak/Xbox-CPU-interposer/tree/main/Hardware

vcore does need to be changed
https://github.com/ACE-AU/OGX-PIII-CPU-VCORE-SETTINGS/blob/main/Xbox%20V1.2-1.4%20VCORE%20Mod.pdf

**Comment by zzattack** [comment]
No longer relevant, it's split into 4 separate 0603 resistors of 1k now.
For older boards, something like https://www.digikey.com/en/products/detail/stackpole-electronics-inc/RAVF164DJT1K00/1744131 can be used.
