### ISSUE TITLE
Help needed to add gerber files to pcb manufacturer

### ISSUE THREAD

**Issue by Sopor** [zzattack/xbox-cpu-interposer#2]
I'm trying to add these gerber files to pcb manufacturer i have found online, but i haven't manage to get it right 😥

I get the interposer and the aligntool correct (I think), but how do i add the stencils?

When i add the stencils i can't select stainless steel and it doesn't look as the right size.

Any help is appreciated 😍

**Comment by zzattack** [comment]
Cannot help with this, best to work it out with your manufacturer
